### ISSUE TITLE
Doc: Textarea are not aligned with code highlight

### ISSUE THREAD

**Issue by houkanshan** [huozhi/devjar#22]
Hey, I think it may be related to the recent change https://github.com/huozhi/devjar/commit/560db6056c7e9ffd00f7e805ec9bd603ded9e9bd, `pre` doesn't look like it needs `padding`.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/657962/169633622-7655ea33-ca47-4e9d-a1c0-e357d020d63e.png">

**Comment by huozhi** [comment]
Thanks for reporting! I've fixed it in #24
