### ISSUE TITLE
code: code first line 

### ISSUE THREAD

**Issue by CooperHash** [huozhi/devjar#49]
![image](https://github.com/huozhi/devjar/assets/73218815/22c01d13-7502-424a-83f5-8597d53e1ef1)

![image](https://github.com/huozhi/devjar/assets/73218815/644eeacb-696d-476d-a8be-55ae34af26eb)

![image](https://github.com/huozhi/devjar/assets/73218815/7692eb6e-7c33-41a7-80e2-01a4b0a4021b)

first line always empty

**Comment by huozhi** [comment]
Fixed, thanks for reporting!
